name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run docs:build
      
      - name: Archive production files
        run: |
          zip -r production-files.zip .
        working-directory: ./docs/.vitepress/dist

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./docs/.vitepress/dist/production-files.zip

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: distfiles

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.4
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: distfiles/*
           target: "${{ secrets.TEMP_DIR }}"
      
      - name: Going Live
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.TEMP_DIR }}
            unzip production-files.zip
            rm production-files.zip
            rm -rf ${{ secrets.DEPLOY_DIR }}/*
            mv distfiles/* ${{ secrets.DEPLOY_DIR }}
            rm -rf ${{ secrets.TEMP_DIR }}